#cloud-config
---
package_update: true
package_upgrade: true

packages:
  - ifupdown
  - htop

write_files:
  - path: /etc/network/interfaces
    content: |
      source /etc/network/interfaces.d/*.cfg
  - path: /etc/network/interfaces.d/01-eth1.cfg
    permissions: "0644"
    content: |
      allow-hotplug eth1
      iface eth1 inet dhcp

runcmd:
  - [ sh, -c, "ifup eth1" ]
