#cloud-config
---
manage_etc_hosts: true
fqdn: ${hostname}

package_update: true
package_upgrade: true

packages:
  - ifupdown
  - htop

write_files:
  - path: /etc/network/interfaces
    content: |
      source /etc/network/interfaces.d/*.cfg
  - path: /etc/network/interfaces.d/01-eth1.cfg
    permissions: "0644"
    content: |
      auto eth1
      iface eth1 inet static
        address ${ip_address}/24

runcmd:
  - [ sh, -c, "ifup eth1" ]
